Repository FECrash/here-your-duckdam, pull requests merged in 2022-09, with the labels that each got.

#5 [페이지] Main, Attitude 페이지 UI 기본 구현
  components/attitude/AttitudeRange.tsx
  components/attitude/AttitudeTitle.tsx
  components/attitude/MessageBox.tsx
  components/attitude/MessageItem.tsx
  components/attitude/index.ts
  components/common/Logo.tsx
  components/layout/Layout.tsx
  pages/attitude/index.tsx
  pages/index.tsx
  public/images/moon_rabbit.png
  styles/animation.ts
  styles/emotion.d.ts
  styles/global.ts
  styles/reset.ts
  styles/theme.ts
Labels: feature, page

#7 [설정] prettier, lint 설정
  .eslintrc.json
  .prettierrc
  .vscode/setting.json
  components/attitude/AttitudeRange.tsx
  components/attitude/AttitudeTitle.tsx
  components/attitude/MessageBox.tsx
  components/attitude/MessageItem.tsx
  components/attitude/index.ts
  components/common/Logo.tsx
  components/layout/Layout.tsx
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/attitude/index.tsx
  pages/index.tsx
  yarn.lock
Labels: setting

#10 [기능구현] Splash 화면 Portal 작업
  components/common/BackDrop.tsx
  components/common/Logo.tsx
  components/common/Portal.tsx
  components/common/index.ts
  components/layout/Layout.tsx
  components/main/AttitudeRange.tsx
  components/main/AttitudeTitle.tsx
  components/main/MessageBox.tsx
  components/main/MessageItem.tsx
  components/main/SplashRabbit.tsx
  components/main/index.ts
  next.config.js
  pages/_document.tsx
  pages/attitude/index.tsx
  pages/index.tsx
  public/images/moon_rabbit.png
  styles/global.ts
Labels: feature

#9 [기능구현] firebase 세팅 및 API 추가
  .firebaserc
  .gitignore
  firebase.json
  package-lock.json
  package.json
  pages/api/duckdam.add.ts
  pages/api/duckdam.get.ts
  storage.rules
  utils/firebase.ts
  yarn.lock
Labels: feature

#17 [버그수정] 덕담 조회, 추가 API 에러 수정
  pages/api/duckdam.get.ts
  pages/api/duckdam/[id].ts
  pages/api/duckdam/add.ts
Labels: bug

#18 [버그수정] animation 동작 화면 레이아웃 오류 수정
  components/common/Logo.tsx
  components/main/MessageItem.tsx
  styles/animation.ts
  styles/global.ts
  styles/keyframe/Keyframe.ts
  styles/keyframe/Keyframe.types.ts
  styles/keyframe/index.ts
  tsconfig.json
Labels: 🐞 버그

#21 [기능구현] 덕담 자동 생성 구현
  components/attitude/AttitudeRange.tsx
  components/attitude/AttitudeTitle.tsx
  components/attitude/MessageBox.tsx
  components/attitude/MessageItem.tsx
  components/attitude/SplashRabbit.tsx
  components/attitude/index.ts
  components/common/index.ts
  components/layout/Layout.tsx
  hooks/useAttitudeHooks.ts
  pages/attitude/index.tsx
  pages/index.tsx
  pages/load/index.tsx
  pages/secret/index.tsx
  shared/constant/CardMessage.ts
  shared/types/DuckDam.ts
  shared/utils/duckdamGenerator.ts
  shared/utils/randomNumber.ts
  tsconfig.json
Labels: 🕹️ 기능

#22 [기능구현] 결과 조회 페이지 open graph 추가
  .gitignore
  components/[resultId]/index.ts
  components/layout/Layout.tsx
  components/result/Card.tsx
  components/result/Links.tsx
  components/result/index.ts
  components/secret/index.ts
  pages/[resultId]/index.tsx
  pages/result/[resultId].tsx
  pages/result/index.tsx
Labels: 🕹️ 기능

#27 [기능구현] 트위터 공유하기 기능 추가
  components/result/Links.tsx
  components/result/index.ts
  pages/result/[resultId].tsx
Labels: 🕹️ 기능

#29 [리팩터링] head 공통 컴포넌트 추가
  components/common/MetaHead.tsx
  components/layout/Layout.tsx
  pages/secret/[resultId].tsx
Labels: ⬆️ 리팩토링

#28 [퍼블리싱] 아이콘, Custom Input, Message
  components/attitude/AttitudeRange.tsx
  components/attitude/AttitudeTitle.tsx
  components/attitude/MessageBox.tsx
  components/attitude/MessageItem.tsx
  components/attitude/index.ts
  components/common/Logo.tsx
  components/layout/Bottom.tsx
  components/layout/Layout.tsx
  components/layout/index.ts
  pages/attitude/index.tsx
  pages/index.tsx
  pages/load/index.tsx
  pages/result/[resultId].tsx
  public/icons/duckdam-package.svg
  public/icons/main-logo_light.svg
  styles/emotion.d.ts
  styles/theme.ts
Labels: 📱 UI

#31 [기능 구현] 404, 500 error page
  components/attitude/MessageBox.tsx
  components/attitude/MessageItem.tsx
  pages/404.tsx
  pages/500.tsx
  pages/load/index.tsx
Labels: 🕹️ 기능

#34 [버그수정] 메타태그 og:image 매핑 오류 수정
  components/common/MetaHead.tsx
  pages/result/[resultId].tsx
Labels: 🐞 버그

#35 [퍼블리싱] 디자인 반영하여 퍼블리싱 수정
  components/attitude/AttitudeRange.tsx
  components/attitude/MessageBox.tsx
  components/attitude/MessageItem.tsx
  components/common/Button.tsx
  components/common/Description.tsx
  components/common/EmojiTitle.tsx
  components/common/Logo.tsx
  components/common/MessageBox.tsx
  components/common/Title.tsx
  components/common/index.ts
  components/result/Card.tsx
  components/result/LinkCopyButton.tsx
  components/result/Links.tsx
  pages/404.tsx
  pages/500.tsx
  pages/attitude/index.tsx
  pages/index.tsx
  pages/result/[resultId].tsx
  pages/secret/[resultId].tsx
  public/icons/cloud1.svg
  public/icons/cloud2.svg
  public/icons/main-logo_light.svg
  public/icons/star1.svg
  public/icons/star2.svg
  styles/reset.ts
Labels: 📱 UI

#38 [기능구현] random 이미지 추가
  pages/load/index.tsx
  shared/utils/getStorageImage.ts
Labels: 🕹️ 기능

#39 [기능구현] 첫번째 덕담 랜덤으로 생성하여 open graph 이미지 설정
  pages/load/index.tsx
  shared/utils/duckdamGenerator.ts
  shared/utils/getStorageImage.ts
Labels: 🕹️ 기능

#40 [UI/UX] Custom Range 컴포넌트 UX 수정
  components/attitude/AttitudeRange.tsx
  components/attitude/MessageBox.tsx
  shared/constant/CardMessage.ts
Labels: 📱 UI

#42 [UI/UX] 덕담 달 favicon
  components/common/MetaHead.tsx
  public/favicon.ico
  public/favicon.svg
Labels: 📱 UI

#36 [UI/UX]로딩 화면 디자인 변경 및 컴포넌트 에니메이션 추가
  components/common/LoadingLogo.tsx
  components/common/index.ts
  pages/load/index.tsx
  public/icons/cloud3.svg
  public/icons/cloud4.svg
  public/icons/duckdam-package.svg
  public/icons/index.ts
  public/icons/loading.gif
  public/icons/loadingBg.png
  public/icons/loadingBgWithoutCircle.png
  public/icons/moon.png
  public/icons/star4.svg
  public/icons/star6.svg
  public/icons/star7.svg
Labels: 📱 UI

#43 fix: 클립보드 복사 모바일에서도 정상작동되도록 수정
  components/result/LinkCopyButton.tsx
  pages/result/[resultId].tsx
Labels: 🐞 버그

#46 [hotfix] 레이아웃 깨지는 오류 수정
  components/common/LoadingLogo.tsx
  components/layout/Layout.tsx
  pages/index.tsx
  pages/load/index.tsx
  pages/result/[resultId].tsx
  public/icons/index.ts
  public/icons/loadingBgWithoutCircle.png
Labels: 📱 UI

#47 [hotfix] 유교수치 메세지에 반영되도록 수정
  components/attitude/AttitudeRange.tsx
  hooks/useAttitudeHooks.ts
  pages/load/index.tsx
  shared/utils/duckdamGenerator.ts
Labels: 🐞 버그

#49 [리팩토링] 이미지 퍼포먼스 관련 리팩토링
  components/common/LoadingLogo.tsx
  components/common/Logo.tsx
  components/common/MetaHead.tsx
  pages/index.tsx
  pages/load/index.tsx
  public/icons/main-logo_light.png
  public/icons/main-logo_light.svg
  public/images/favicon.ico
  public/images/loading-done.gif
  public/images/moon_rabbit.png
  public/vercel.svg
Labels: ⬆️ 리팩토링

#50 [리팩토링] 코드 1차 리팩토링
  .eslintrc.json
  components/attitude/MessageItem.tsx
  components/common/Button.tsx
  components/common/index.ts
  components/layout/Layout.tsx
  pages/api/duckdam/[id].ts
  pages/api/duckdam/add.ts
  pages/attitude/index.tsx
  pages/index.tsx
  pages/result/[resultId].tsx
  pages/secret/[resultId].tsx
  shared/hooks/useAttitudeHooks.ts
  shared/types/DuckDam.ts
  shared/utils/duckdamGenerator.ts
  shared/utils/firebase.ts
  shared/utils/getStorageImage.ts
  styles/index.ts
  styles/keyframe/Keyframe.ts
  styles/keyframe/Keyframe.types.ts
  styles/keyframe/index.ts
Labels: ⬆️ 리팩토링

#54 [리팩토링] 코드 2차 리팩토링
  components/attitude/AttitudeRange.tsx
  components/attitude/SplashRabbit.tsx
  components/attitude/index.ts
  components/common/BackDrop.tsx
  components/common/LoadingLogo.tsx
  components/common/Logo.tsx
  components/common/MetaHead.tsx
  components/common/Portal.tsx
  components/common/index.ts
  components/layout/Layout.tsx
  components/result/Card.tsx
  components/result/LinkCopyButton.tsx
  components/result/Links.tsx
  components/result/index.ts
  pages/404.tsx
  pages/500.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/attitude/index.tsx
  pages/index.tsx
  pages/load/index.tsx
  pages/result/[resultId].tsx
  public/favicon.svg
  public/icons/cloud1.svg
  public/icons/cloud2.svg
  public/icons/cloud3.svg
  public/icons/cloud4.svg
  public/icons/duckdam-package.png
  public/icons/duckdam-package.svg
  public/icons/index.ts
  public/icons/loading-background.png
  public/icons/loadingBg.png
  public/icons/main-logo-light.png
  public/icons/star1.svg
  public/icons/star2.svg
  public/icons/star4.svg
  public/icons/star6.svg
  public/icons/star7.svg
  public/images/background.png
  public/images/copy-icon.svg
  shared/constant/StorageImageUrl.ts
  shared/hooks/useDuckdam.ts
  shared/hooks/useKakao.ts
  shared/types/SharedKakao.ts
  shared/utils/getStorageImage.ts
  styles/theme.ts
Labels: ⬆️ 리팩토링

#55 [기능구현] 구글 애널리틱스 추가
  global.d.ts
  pages/_app.tsx
  shared/utils/gtag.ts
Labels: 🕹️ 기능
